title: Verschaeve Dries - Cloud solution architect
email: dries.verschaeve@vddesign.be
description: >-
  None
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.vddesign.be" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dverschaeve
github_username:  dverschaeve


# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blue # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

paginate: 6
paginate_path: /page:num/

analytics: true
